USE [master]
GO
/****** Object:  Database [BeyondOneTestDB]    Script Date: 3/24/2022 2:56:29 PM ******/
CREATE DATABASE [BeyondOneTestDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BeyondOneTestDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER2019\MSSQL\DATA\BeyondOneTestDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BeyondOneTestDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER2019\MSSQL\DATA\BeyondOneTestDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [BeyondOneTestDB] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BeyondOneTestDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [BeyondOneTestDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [BeyondOneTestDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [BeyondOneTestDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [BeyondOneTestDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [BeyondOneTestDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [BeyondOneTestDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [BeyondOneTestDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [BeyondOneTestDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [BeyondOneTestDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [BeyondOneTestDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [BeyondOneTestDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [BeyondOneTestDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [BeyondOneTestDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [BeyondOneTestDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [BeyondOneTestDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [BeyondOneTestDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [BeyondOneTestDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [BeyondOneTestDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [BeyondOneTestDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [BeyondOneTestDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [BeyondOneTestDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [BeyondOneTestDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [BeyondOneTestDB] SET RECOVERY FULL 
GO
ALTER DATABASE [BeyondOneTestDB] SET  MULTI_USER 
GO
ALTER DATABASE [BeyondOneTestDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [BeyondOneTestDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [BeyondOneTestDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [BeyondOneTestDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [BeyondOneTestDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [BeyondOneTestDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'BeyondOneTestDB', N'ON'
GO
ALTER DATABASE [BeyondOneTestDB] SET QUERY_STORE = OFF
GO
USE [BeyondOneTestDB]
GO
/****** Object:  Table [dbo].[Products]    Script Date: 3/24/2022 2:56:30 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Products](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ProductID] [varchar](12) NOT NULL,
	[ProductName] [varchar](250) NOT NULL,
	[StockAvailable] [int] NOT NULL,
	[CreatedDateTime] [datetime] NOT NULL,
	[UpdateDateTime] [datetime] NULL,
 CONSTRAINT [PK_Products] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Products] ON 
GO
INSERT [dbo].[Products] ([ID], [ProductID], [ProductName], [StockAvailable], [CreatedDateTime], [UpdateDateTime]) VALUES (1, N'999', N'wewrw', 145, CAST(N'2022-03-24T14:11:56.893' AS DateTime), CAST(N'2022-03-24T14:23:17.153' AS DateTime))
GO
INSERT [dbo].[Products] ([ID], [ProductID], [ProductName], [StockAvailable], [CreatedDateTime], [UpdateDateTime]) VALUES (2, N'112', N'test123', 0, CAST(N'2022-03-24T14:12:51.940' AS DateTime), NULL)
GO
SET IDENTITY_INSERT [dbo].[Products] OFF
GO
USE [master]
GO
ALTER DATABASE [BeyondOneTestDB] SET  READ_WRITE 
GO
